### ISSUE TITLE
 Azuracast

### ISSUE THREAD

**Issue by suricloud** [caprover/one-click-apps#637] opened 2022-03-15 01:45 UTC
Hi,
Can you azuracast to the apps list please?

**Comment by RisKatOr** [comment] 2023-10-20 20:14
It would be great, I can’t install it in other possible ways (via ImageName, Github..), it gives an error 502 Bad Gateway.

**Comment by githubsaturn** [comment] 2023-10-21 02:23
Dupe of https://github.com/caprover/one-click-apps/issues/151#issuecomment-1773343185

**Closed by githubsaturn** 2023-10-21 02:23 UTC
