### ISSUE TITLE
Regex on Sentry doesn't allow keys generated by Sentry

### ISSUE THREAD

**Issue by jakcharlton** [caprover/one-click-apps#87] opened 2019-08-14 07:07 UTC
The regex is:
> ^(?> =.*\d)(?=.*[a-z])(?=.*[A-Z])[0-9a-zA-Z]{50,}$

A key generated by Sentry looks like:

docker run --rm sentry config generate-secret-key
> )%xpp06ugqbu72dt#(yjq48!&qqnptz^xjk9a9&0b^dzcu7e@+

**Comment by githubsaturn** [comment] 2019-08-14 15:35
@aldaircruz 
Would you be able to look into this please?

**Comment by jakcharlton** [comment] 2019-08-14 22:31
May also be worth checking the password regex's as both are hugely
restrictive (only letters and numbers, very long)

**Comment by aldaircruz** [comment] 2019-08-22 19:02
Hi @jakcharlton thanks for pointing this out.
@githubsaturn I will have a look into this!

**Comment by githubsaturn** [comment] 2019-08-23 00:36
Thanks to @aldaircruz this is patched. Please check again and let me know if the issue is resolved so we can close this issue.

PS: No need to update your CapRover. One-click apps dynamically get pulled from the this repo.

**Comment by jakcharlton** [comment] 2019-08-23 01:04
Much appreciated, sadly I won't have time to check in the near future, I
moved on from using sentry ... probably safe to assume it's resolved though

**Closed** 2019-08-23 13:22 UTC
