### ISSUE TITLE
App Suggestion: ToolJet

### ISSUE THREAD

**Issue by gdassori** [caprover/one-click-apps#917] opened 2023-04-28 09:30 UTC
#### ToolJet 

ToolJet is an open-source low-code framework to build and deploy internal tools quickly with minimal engineering effort. ToolJet's drag and drop frontend builder allows you to build complicated responsive frontends within minutes. You can also connect to your data sources, such as databases ( PostgreSQL, MongoDB, Elasticsearch & more), API endpoints (ToolJet supports importing OpenAPI spec & OAuth2 authorization), SaaS tools (Stripe, Slack, Google Sheets, Airtable, Notion & more) and object storage services ( S3, GCS, Minio, etc ) to fetch and write data.

There is a docker-compose file available with multiple containers that need to be deployed and a folder with all the docker files.

https://github.com/ToolJet/ToolJet
https://github.com/ToolJet/ToolJet/tree/develop/docker

**Comment by githubsaturn** [comment] 2023-04-29 16:03
Dupe of https://github.com/caprover/one-click-apps/issues/795

**Closed by githubsaturn** 2023-04-29 16:03 UTC
