### ISSUE TITLE
App Suggestion: Authelia

### ISSUE THREAD

**Issue by ReallySnazzy** [caprover/one-click-apps#912] opened 2023-04-22 10:14 UTC
**Please tell us what app you'd like to see on CapRover as a one-click app.**
[Authelia](https://www.authelia.com) is a self hosted SSO service that is lightweight and open source. 

**Do you know if there is any official Docker image for the app?**
https://hub.docker.com/r/authelia/authelia

**Comment by githubsaturn** [comment] 2023-04-22 18:04
Dupe of https://github.com/caprover/one-click-apps/issues/892

**Closed by githubsaturn** 2023-04-22 18:04 UTC
