### ISSUE TITLE
App Suggestion: Discourse

### ISSUE THREAD

**Issue by r-chris** [caprover/one-click-apps#184] opened 2020-06-11 08:05 UTC
**Please tell us what app you'd like to see on CapRover as a one-click app.**

Discourse

A platform for community discussion. Free, open, simple. https://www.discourse.org

**Do you know if there is any official Docker image for the app?**

Yes. Docker is the only officially supported option to install Discourse.

https://github.com/discourse/discourse/blob/master/docs/INSTALL.md
https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md

https://github.com/discourse/discourse_docker

https://hub.docker.com/_/discourse

This is the official Discourse image, to use it you must use our launcher tool:
https://hub.docker.com/r/discourse/base

**Comment by githubsaturn** [comment] 2020-06-11 12:57
Duplicate of : https://github.com/caprover/one-click-apps/issues/13

**Closed by githubsaturn** 2020-06-11 12:57 UTC

**Comment by r-chris** [comment] 2020-06-11 13:18
Thanks - not sure how I missed that!
