### ISSUE TITLE
App Suggestion: supabase

### ISSUE THREAD

**Issue by QThans** [caprover/one-click-apps#1122] opened 2024-06-23 08:02 UTC
**Please tell us what app you'd like to see on CapRover as a one-click app.**
Supabase

**Do you know if there is any official Docker image for the app?**
https://github.com/supabase/supabase/blob/master/docker/

**Comment by githubsaturn** [comment] 2024-06-23 16:59
Dupe of https://github.com/caprover/one-click-apps/issues/515

**Closed by githubsaturn** 2024-06-23 16:59 UTC
